services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - ./static/uploads:/app/caremed/static/uploads

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: caremed_db
      MYSQL_USER: caremed_user
      MYSQL_PASSWORD: C@reMed_@2026@ppMYSQL
      MYSQL_ROOT_PASSWORD: MYSQLrootp@ssword@2123
    command: [
      "mysqld",
      "--innodb_buffer_pool_size=64M",
      "--key_buffer_size=16M",
      "--max_connections=50"
    ]
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: