"""Added a cost price

Revision ID: 115949e39548
Revises: bbe226a61ef2
Create Date: 2026-06-11 19:52:19.019567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115949e39548'
down_revision = 'bbe226a61ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('cost_price')

    # ### end Alembic commands ###
