"""Added Tracking Status

Revision ID: 1a8474776e5e
Revises: f0f0c7f19838
Create Date: 2026-05-05 22:56:56.661473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8474776e5e'
down_revision = 'f0f0c7f19838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('tracking_status')

    # ### end Alembic commands ###
