"""Fix rental financial fields

Revision ID: 1b2ce3d19b68
Revises: 4a081aeed39b
Create Date: 2026-04-03 19:44:47.857853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b2ce3d19b68'
down_revision = '4a081aeed39b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.alter_column('monthly_rate',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.alter_column('monthly_rate',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
