"""add purchase snapshot fields

Revision ID: 1d479cf84683
Revises: c21ea146226b
Create Date: 2026-06-13 22:36:31.682803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d479cf84683'
down_revision = 'c21ea146226b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('product_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('product_category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('product_cost_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('product_sale_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('product_rent_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('product_rent_period', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_column('product_rent_period')
        batch_op.drop_column('product_rent_price')
        batch_op.drop_column('product_sale_price')
        batch_op.drop_column('product_cost_price')
        batch_op.drop_column('product_category')
        batch_op.drop_column('product_image')
        batch_op.drop_column('product_description')

    # ### end Alembic commands ###
