"""Remove Birthday

Revision ID: 1de961470353
Revises: c7c2c6f72fdf
Create Date: 2026-06-10 21:07:26.612998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1de961470353'
down_revision = 'c7c2c6f72fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('birthday')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
