"""Added Payment type

Revision ID: 20963b572151
Revises: 4e67bb2d8919
Create Date: 2026-08-27 22:32:05.162632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20963b572151'
down_revision = '4e67bb2d8919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_type', sa.String(length=50), nullable=False))
        batch_op.create_index(batch_op.f('ix_payments_payment_type'), ['payment_type'], unique=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_is_refillable'), ['is_refillable'], unique=False)

    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rental_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rental_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rental_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_rental_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_transaction_type'), ['transaction_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_transaction_status'))
        batch_op.drop_index(batch_op.f('ix_transaction_product_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_customer_id'))

    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rental_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_rental_status'))
        batch_op.drop_index(batch_op.f('ix_rental_product_id'))
        batch_op.drop_index(batch_op.f('ix_rental_customer_id'))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_is_refillable'))
        batch_op.drop_index(batch_op.f('ix_product_is_active'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_payment_type'))
        batch_op.drop_column('payment_type')

    # ### end Alembic commands ###
