"""add quantity_returned to rental

Revision ID: 352c4132bc43
Revises: a1e96caff0c3
Create Date: 2026-06-11 01:46:21.237986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '352c4132bc43'
down_revision = 'a1e96caff0c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_returned', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.drop_column('quantity_returned')

    # ### end Alembic commands ###
