"""Added Tank Log

Revision ID: 35cdeb4ba8eb
Revises: e9ed2dbfdac7
Create Date: 2026-08-08 13:16:10.547472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35cdeb4ba8eb'
down_revision = 'e9ed2dbfdac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_tank_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rental_id', sa.Integer(), nullable=False),
    sa.Column('tank_id', sa.Integer(), nullable=True),
    sa.Column('old_serial_number', sa.String(length=100), nullable=True),
    sa.Column('new_serial_number', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rental_id'], ['rental.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tank_id'], ['rental_tank.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rental_tank_log')
    # ### end Alembic commands ###
