"""Add new Table for forgot password

Revision ID: 387a4b1f91a8
Revises: b2edcf255c61
Create Date: 2026-03-11 19:17:20.470586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '387a4b1f91a8'
down_revision = 'b2edcf255c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_otp_code', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_attempts', sa.Integer(), nullable=True))
        batch_op.drop_column('reset_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_code', mysql.VARCHAR(length=6), nullable=True))
        batch_op.drop_column('reset_attempts')
        batch_op.drop_column('reset_otp_code')

    # ### end Alembic commands ###
