"""empty message

Revision ID: 3d92f38aad1b
Revises: 27a356bda2c8
Create Date: 2026-03-20 20:27:09.916559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d92f38aad1b'
down_revision = '27a356bda2c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_path', sa.String(length=255), nullable=True))
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('profile_path')

    # ### end Alembic commands ###
