"""add rental invoice table

Revision ID: 4a081aeed39b
Revises: 98cddbd28082
Create Date: 2026-04-02 19:15:51.181039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a081aeed39b'
down_revision = '98cddbd28082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rental_id', sa.Integer(), nullable=False),
    sa.Column('service_period_start', sa.Date(), nullable=False),
    sa.Column('service_period_end', sa.Date(), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('late_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['rental_id'], ['rental.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'rental_invoice', ['invoice_id'], ['id'])

    with op.batch_alter_table('security_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('severity', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_logs', schema=None) as batch_op:
        batch_op.drop_column('severity')
        batch_op.drop_column('user_agent')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('invoice_id')

    op.drop_table('rental_invoice')
    # ### end Alembic commands ###
