"""add expense_title and recorded_by to expenses

Revision ID: 4acab3b7962f
Revises: 6b1658cbf5d3
Create Date: 2026-06-12 15:25:57.100502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4acab3b7962f'
down_revision = '6b1658cbf5d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expense_title', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('expense_title')

    # ### end Alembic commands ###
