"""Add is_open_duration column to Rental model

Revision ID: 4e67bb2d8919
Revises: 963e8efe5b2c
Create Date: 2026-08-15 19:39:21.929099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e67bb2d8919'
down_revision = '963e8efe5b2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_open_duration', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.drop_column('is_open_duration')

    # ### end Alembic commands ###
