"""Added New Column

Revision ID: 55ece3c30fc1
Revises: aa5484e47b1d
Create Date: 2026-03-27 22:30:35.271553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ece3c30fc1'
down_revision = 'aa5484e47b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_empty', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_refillable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deposit_refunded', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('return_condition_img', sa.String(length=255), nullable=True))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fulfillment_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('delivery_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('delivery_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('landmark', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('landmark')
        batch_op.drop_column('delivery_address')
        batch_op.drop_column('delivery_status')
        batch_op.drop_column('fulfillment_type')

    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.drop_column('return_condition_img')
        batch_op.drop_column('delivery_fee')
        batch_op.drop_column('is_deposit_refunded')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('is_refillable')
        batch_op.drop_column('stock_empty')

    # ### end Alembic commands ###
