"""Added A Table RentalTank

Revision ID: 5a7a43ea3cd0
Revises: 6689bdf114b9
Create Date: 2026-08-07 02:02:20.190866

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a7a43ea3cd0'
down_revision = '6689bdf114b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_tank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rental_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['rental_id'], ['rental.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.drop_column('serial_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial_number', mysql.TEXT(), nullable=True))

    op.drop_table('rental_tank')
    # ### end Alembic commands ###
