"""Added A serial number for tank in a rent

Revision ID: 5ca6dd3e27ef
Revises: 1de961470353
Create Date: 2026-06-11 00:50:48.117358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ca6dd3e27ef'
down_revision = '1de961470353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial_number', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.drop_column('serial_number')

    # ### end Alembic commands ###
