"""add refillTransaction

Revision ID: 6123551676fb
Revises: a162fcbebed0
Create Date: 2026-07-06 22:17:05.339959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6123551676fb'
down_revision = 'a162fcbebed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refill_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('walk_in_name', sa.String(length=255), nullable=True),
    sa.Column('walk_in_tank_size', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('refill_cost_per_unit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('serial_numbers', sa.Text(), nullable=False),
    sa.Column('processed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['processed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refill_transaction')
    # ### end Alembic commands ###
