"""added Permissions

Revision ID: 629a17f86028
Revises: 1d479cf84683
Create Date: 2026-06-24 22:34:46.607264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629a17f86028'
down_revision = '1d479cf84683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('can_manage_customers', sa.Boolean(), nullable=True),
    sa.Column('can_verify_customers', sa.Boolean(), nullable=True),
    sa.Column('can_manage_products', sa.Boolean(), nullable=True),
    sa.Column('can_update_stock', sa.Boolean(), nullable=True),
    sa.Column('can_process_transactions', sa.Boolean(), nullable=True),
    sa.Column('can_confirm_payments', sa.Boolean(), nullable=True),
    sa.Column('can_export_transactions', sa.Boolean(), nullable=True),
    sa.Column('can_manage_expenses', sa.Boolean(), nullable=True),
    sa.Column('can_view_reports', sa.Boolean(), nullable=True),
    sa.Column('can_view_logs', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permission')
    # ### end Alembic commands ###
