"""add password_last_reset_at

Revision ID: 6b1658cbf5d3
Revises: 805ab38b0b00
Create Date: 2026-06-04 20:57:33.196125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b1658cbf5d3'
down_revision = '805ab38b0b00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_last_reset_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_last_reset_at')

    # ### end Alembic commands ###
