"""Added new Column in Customer

Revision ID: 6db0591b4d35
Revises: c01c1bb0342d
Create Date: 2026-03-25 19:39:51.517196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6db0591b4d35'
down_revision = 'c01c1bb0342d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_id_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('secondary_id_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('secondary_id_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('secondary_id_path')
        batch_op.drop_column('secondary_id_type')
        batch_op.drop_column('primary_id_type')

    # ### end Alembic commands ###
