"""Merge refill fields into transaction table and drop refill_transaction

Revision ID: 7e2925f423c0
Revises: d852b40e9d15
Create Date: 2026-08-08 19:18:45.083002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e2925f423c0'
down_revision = 'd852b40e9d15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refill_transaction')
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('refill_cost_per_unit', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('serial_numbers', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('walk_in_tank_size', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('walk_in_tank_size')
        batch_op.drop_column('serial_numbers')
        batch_op.drop_column('refill_cost_per_unit')
        batch_op.drop_column('quantity')
        batch_op.drop_column('product_id')

    op.create_table('refill_transaction',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('walk_in_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('walk_in_tank_size', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('total_revenue', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('refill_cost_per_unit', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('serial_numbers', mysql.TEXT(), nullable=False),
    sa.Column('processed_by_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('refill_transaction_ibfk_1')),
    sa.ForeignKeyConstraint(['processed_by_id'], ['users.id'], name=op.f('refill_transaction_ibfk_2')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('refill_transaction_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
