"""change Contact Number

Revision ID: 805ab38b0b00
Revises: 34f220ba7611
Create Date: 2026-06-03 20:46:58.970724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805ab38b0b00'
down_revision = '34f220ba7611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secondary_contact_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('secondary_contact_number')

    # ### end Alembic commands ###
