"""Added Table of Customer Deposit

Revision ID: 84cb0ad52ee2
Revises: cafa1683d263
Create Date: 2026-09-19 23:35:57.076631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84cb0ad52ee2'
down_revision = 'cafa1683d263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_deposit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_deposit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_deposit_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_deposit_status'), ['status'], unique=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposit_amount', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('deposit_amount')

    with op.batch_alter_table('customer_deposit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_deposit_status'))
        batch_op.drop_index(batch_op.f('ix_customer_deposit_customer_id'))

    op.drop_table('customer_deposit')
    # ### end Alembic commands ###
