"""add can_view_active_rentals to permission

Revision ID: 858e104c4046
Revises: ba141536d079
Create Date: 2026-06-30 08:40:03.581835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858e104c4046'
down_revision = 'ba141536d079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_view_active_rentals', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_column('can_view_active_rentals')

    # ### end Alembic commands ###
