"""Added New Column for Valid ID

Revision ID: 89cf447ec941
Revises: 7f87beba6e46
Create Date: 2026-03-23 16:23:35.567017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89cf447ec941'
down_revision = '7f87beba6e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valid_id_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('id_uploaded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_id_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('is_id_verified')
        batch_op.drop_column('id_uploaded_at')
        batch_op.drop_column('valid_id_path')

    # ### end Alembic commands ###
