"""Added New Initial Fill for Oxygen Tank Content

Revision ID: 963e8efe5b2c
Revises: 7e2925f423c0
Create Date: 2026-08-09 22:12:35.941701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963e8efe5b2c'
down_revision = '7e2925f423c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_initial_fill', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('initial_fill_cost', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('initial_fill_cost')
        batch_op.drop_column('has_initial_fill')

    # ### end Alembic commands ###
