"""Adjust the way Product deleted

Revision ID: 9826ba79e3e3
Revises: a8e1c0b49308
Create Date: 2026-06-11 22:00:20.503715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9826ba79e3e3'
down_revision = 'a8e1c0b49308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('product_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('product_asset_tag', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('product_condition', sa.String(length=50), nullable=True))
        batch_op.drop_constraint(batch_op.f('purchase_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('purchase_ibfk_2'), 'product', ['product_id'], ['id'])
        batch_op.drop_column('product_condition')
        batch_op.drop_column('product_asset_tag')
        batch_op.drop_column('product_type')
        batch_op.drop_column('product_name')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('archived_at')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
