"""Connecting Transaction and Paymets Table

Revision ID: a136888cea05
Revises: f54dc372b4ed
Create Date: 2026-03-30 00:00:31.091997

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a136888cea05'
down_revision = 'f54dc372b4ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_type', sa.String(length=20), nullable=True))
        batch_op.drop_column('offer_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offer_type', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('transaction_type')

    # ### end Alembic commands ###
