"""added tank status

Revision ID: a1e96caff0c3
Revises: 5ca6dd3e27ef
Create Date: 2026-06-11 01:32:11.229390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e96caff0c3'
down_revision = '5ca6dd3e27ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tank_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('total_owned', sa.Integer(), nullable=True),
    sa.Column('rented_out', sa.Integer(), nullable=True),
    sa.Column('full_in_stock', sa.Integer(), nullable=True),
    sa.Column('empty_in_stock', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tank_status')
    # ### end Alembic commands ###
