"""Added Gender and Birthday column in customer table

Revision ID: b8e687da221d
Revises: c13b4addc31c
Create Date: 2026-03-24 23:28:34.647825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e687da221d'
down_revision = 'c13b4addc31c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('birthday')

    # ### end Alembic commands ###
