"""Added: Offer Type and One Column for Pricelist

Revision ID: c1aa674e4bfc
Revises: 
Create Date: 2026-03-29 14:44:40.778085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1aa674e4bfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offer_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('rent_period', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('rent_period')
        batch_op.drop_column('offer_type')

    # ### end Alembic commands ###
