"""Remove And Added Proof of Bailling Path

Revision ID: c7c2c6f72fdf
Revises: fbf5c52b0cec
Create Date: 2026-06-10 20:18:22.413409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7c2c6f72fdf'
down_revision = 'fbf5c52b0cec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('proof_of_billing_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proof_of_billing_type', mysql.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
