"""Make the rent and selling Price nullable=True

Revision ID: cc39d7cb999a
Revises: b85eae615523
Create Date: 2026-03-28 23:37:01.845236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc39d7cb999a'
down_revision = 'b85eae615523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('sale_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('rent_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('rent_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('sale_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)

    # ### end Alembic commands ###
