"""Change Model to Name

Revision ID: d1c30751f7ac
Revises: 1b2ce3d19b68
Create Date: 2026-04-06 13:16:46.539620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1c30751f7ac'
down_revision = '1b2ce3d19b68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.drop_column('model')

    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.alter_column('monthly_rate',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('monthly_rate',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
