"""Initalize new Table

Revision ID: d446ed2db588
Revises: 
Create Date: 2026-03-26 15:03:11.022233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd446ed2db588'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('customer_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('customer_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warranty_or_notes', sa.Text(), nullable=True))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('processed_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('transaction_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['processed_by'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('transaction_ibfk_2'), 'users', ['processed_by'], ['id'])
        batch_op.alter_column('processed_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_column('warranty_or_notes')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('customer_ibfk_2'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('customer_ibfk_1'), 'users', ['created_by_id'], ['id'])

    # ### end Alembic commands ###
