"""empty message

Revision ID: d7a12f8d78a0
Revises: 59c4f32727e5
Create Date: 2026-03-08 19:47:40.528364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a12f8d78a0'
down_revision = '59c4f32727e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('lock_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('role')
        batch_op.drop_column('lock_reason')
        batch_op.drop_column('email_verified_at')
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('oauth_provider')

    # ### end Alembic commands ###
