"""Added New Column for Valid ID

Revision ID: d7ba7428f344
Revises: 89cf447ec941
Create Date: 2026-03-23 19:39:50.486949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7ba7428f344'
down_revision = '89cf447ec941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('contact_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('home_address', sa.String(length=255), nullable=True))
        batch_op.drop_column('contact')
        batch_op.drop_column('name')
        batch_op.drop_column('address')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('first_name')
        batch_op.drop_column('reset_attempts')
        batch_op.drop_column('password_last_reset_at')
        batch_op.drop_column('last_name')
        batch_op.drop_column('phone')
        batch_op.drop_column('address')
        batch_op.drop_column('profile_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_path', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('last_name', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('password_last_reset_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('reset_attempts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('first_name', mysql.VARCHAR(length=50), nullable=True))

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('contact', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('home_address')
        batch_op.drop_column('contact_number')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
