"""Added Delivery Fee

Revision ID: d852b40e9d15
Revises: 35cdeb4ba8eb
Create Date: 2026-08-08 17:58:32.804996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd852b40e9d15'
down_revision = '35cdeb4ba8eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('delivery_fee')

    # ### end Alembic commands ###
