"""Date For Rent

Revision ID: e8ed65768be1
Revises: 060857b83b6b
Create Date: 2026-04-22 00:18:17.709937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ed65768be1'
down_revision = '060857b83b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rental_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('rental_duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_column('rental_duration')
        batch_op.drop_column('rental_start_date')

    # ### end Alembic commands ###
