"""Added Voucher Amount

Revision ID: e9ed2dbfdac7
Revises: 5a7a43ea3cd0
Create Date: 2026-08-08 12:56:54.795535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9ed2dbfdac7'
down_revision = '5a7a43ea3cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voucher_amount', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('voucher_amount')

    # ### end Alembic commands ###
