"""Connecting Transaction and Paymets Table

Revision ID: f54dc372b4ed
Revises: c1aa674e4bfc
Create Date: 2026-03-29 22:18:33.797686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f54dc372b4ed'
down_revision = 'c1aa674e4bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('payments_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'transaction', ['transaction_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payments_ibfk_1'), 'transaction', ['transaction_id'], ['id'])

    # ### end Alembic commands ###
