"""Add refill_cost to product

Revision ID: f85a9e78bf66
Revises: b3e7c92f4a15
Create Date: 2026-10-08 08:12:07.620486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f85a9e78bf66'
down_revision = 'b3e7c92f4a15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refill_cost', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('refill_cost')

    # ### end Alembic commands ###
