"""Added Proof Of Bailling

Revision ID: fbf5c52b0cec
Revises: 6b1658cbf5d3
Create Date: 2026-06-10 20:11:29.387596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbf5c52b0cec'
down_revision = '6b1658cbf5d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proof_of_billing_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('proof_of_billing_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('proof_of_billing_path')
        batch_op.drop_column('proof_of_billing_type')

    # ### end Alembic commands ###
